apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../components/autoscale-gpu/aws-gpu-machineset
  - ../../components/keda-scale-machineset
  - ../../components/operators/keda
