apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

components:
  - https://github.com/redhat-na-ssa/demo-ai-gitops-catalog/components/operators/gpu-operator-certified/instance/components/gpu-monitoring?ref=v0.16
  - https://github.com/redhat-na-ssa/demo-ai-gitops-catalog/components/operators/gpu-operator-certified/instance/components/monitoring-dashboard?ref=v0.16
  - time-slicing-2

resources:
  - https://github.com/redhat-na-ssa/demo-ai-gitops-catalog/components/operators/gpu-operator-certified/operator/overlays/stable?ref=v0.16
  - base
